<?php

return [
	'adjudicacion_reserva' => 0,
	'auto_licit' => true,
	'dummy_bidder' => '9999',
	'ArtistCode' => 0,
	'automatic_blocking_licit_cancel_bids' => 10,
	'cd_time' => 3,
	'DeleteOrdersAnyTime' => false,
	'distance_to_play_favs' => 3,
	'dontRemoveBooksOrders' => true,
	'escalado_libre' => false,
	'escalado_libre_pujas' => 0,
	'force_correct_price' => true,
	'not_force_correct_price_tiempo_real' => true,
	'gridHistoricoVentas' => false,
	'group_auction_in_search' => true,
	'hide_not_sell_lot_historical' => false,
	'increase_time_add' => 60,
	'increase_time_launch' => 360,
	'loteFavoritoProximo' => 0,
	'maxium_time_increment' => 0,
	'max_orders_and_bids_ries_cli' => false,
	'max_orders_ries_cli' => false,
	'not_force_correct_price_tiempo_real' => true,
	'notice_over_bid' => false,
	'number_bids_lotlist' => false,
	'paginacion_grid_lotes' => 1,
	'pujas_enfirme' => false,
	'restrictVisibility' => false,
	'search_engine' => false,
	'search_multiple_words' => true,
	'send_email_cancel_bid' => 2,
	'send_email_lot_increment_bid_to_all_users_with_deposit' => false,
	'send_valid_deposit_notification' => false,
	'default_minuts_pause' => 5,
	'search_fields' => '', //Utilizado por Alcala para campos a buscar. @todo grid antiguo
	'search_fields_no_lang' => '', //Utilizado por Alcala para campos a buscar. @todo grid antiguo
	'notifyIfYouNotWinner' => false, //Notificar si la orden no supera la maxima
	'shoppingCart' => null, //Carrito de la compra en las subastas V
	'date_regenerate_image' => null, //fecha en formato Y-m-d, Si una imagen es anterior a esta fecha se regenerara
	'default_order' => 'ref', // Ordern por defecto para el listado de lotes
	'permanent_auction' => false, //Mostrar lotes en listado de permanentes solamente si ha iciado la fecha del lote
	'mail_prop_online' => false, //Enviar mail a propietario al adjudicar lote online
	'hide_return_lot' => false, //No mostrar lotes retirados y devueltos en grid
	'buy_historic' => false, // Permitir la compra de lotes históricos
	'fecha_noindex_follow' => '10/11/2017', //@todo - Eliminar de Empty y bases de datos
	'goGridIfOnlyOneAuction' => false, //Ir a grid de lotes si solo hay una subasta,
	'show_only_not_awarded' => false, // Cuando el filtro de no vendidos está activo, no mostrar devueltos o retirados
	'diferenciarOrdenTelefonicaWeb' => false, // Se marcará la orden telefonica web como una X en vez de una T
	'trAuctionConditions' => false, // Mostrar frase de condiciones en TR y popup al pujar
	'scaleFromPrice' => false, // Escalado en base al precio inicial del lote @todo - No lo tiene nadie, pero vale la pena mantener la lógica.
	'uniqueArtCategory' => '', // indica que solo hay una única categoria en articulos, por lo que los enlaces deben ir siempre a esa
	'getDummyApiBid' => false, // La llamada getBids de la API devuelve todas las pujas, incluso las del licitador 9999
	'ArtistInExibition' => false, //Permite poner en la exposicion un artista, para que se pueda poner por defecto en las obras de la exposicion
	'ArtistNameSurname' => false, // Cuando el nombre está compuesto por "apellido, nombre" , le da la vuelta y escribe "nombre apellido"
	'lang_sub_in_global' => false, // Obtener descripciones de la subasta en la busqueda global para header y footer
	'verify_subscription_before_saving' => false, //Verificar si existe suscripcion a newsletter antes de añadirla de nuevo
	'showCloseLotCategoryGridWithoutCompra' => false, // Mostrar lotes cerrados en categorias aunque no sean para compra
	'substrRef' => 0, //valor en int. limitamos el numero de referencia a esos caracteres, esto se usa para poder sacar varias veces el mism olote a subasta, el contador de las veces que ha salido el lote ira a la izquierda, pro lo que no se debe mostrar
	'AutorInTR' => null, //Id de autor. Poner el autor en el título del lote para que se vea en el tiempo real
	'reserveLot' => 0, //minutos que se reserva el lote en la tienda para que no lo compre ningun cliente
	'email_order_to_admin' => false, // Enviar email de confirmación de puja/orden al administrador.
	'imageRequiredInValoraciones' => true, // Establece la obligación o no de adjuntar fotos en la valoracion de articulos, defecto 1
	'noIVAOnlineAuction' => false, //No se cobrará el iva  de la comisión en la subasta online
	'porcentaje_seguro_envio' => 0, //porcentaje que supone el seguro de envio
	'envio_individual_web_gastos_envio' => null,// Si el lote pertenece a alguna de estas familias se debe enviar por separado, las familias se separan por comas
	'suma_peso_web_gastos_envio' => null, // Array de pesos, si el peso del envio es menor o igual al inidce, se suma X cms e Y kilos, siendo [X,Y] los valores pasados
	'max_lot_web_gastos_envio' => null, // Numero de lotes máximo que podemso juntar en un envio
	'favorites_lotlist' => false, // Favoritos en grid
	'showCloseLotCategoryGrid' => false, // Mostrar los lotes cerrados en el grid de categorias
	'search_all' => false, // En el buscador de la home, buscar en subastas .H y S @todo - grid antiguo
	'search_all_desc' => false, // Filtar por desc y descweb
	'add_email_adjudicado' => false, // Añadir liniea en web_email_closlot para mandar el email del ganador al cerrar un lote en la subasta tipo W, necesita un cron para lanzar lso emails
	'WebServiceRejectOrder' => false, // El webservice puede rechazar la orden
	'checkItp' => false, // Comprobar impuesto de transmision patrimonial en lotes
	'disabled_ries_cli' => false, // No controlar maximo de riesgo en esa subasta
	'ministeryCli' => null, // ID de cliente para el Cliente ministerio
	'ministeryLicit' => null, // Nº paleta de licitador para el ministerio
	'notice_over_bid_email' => false, //Envia email over_bid cuando se realice una orden existiendo una superior
	'time_to_automatic_blocking_licit_cancel_bids' => 0, //Segundos necesarios desde el momento actual, para contar pujas canceladas antes de bloquear usuario
	'use_credit' => false, // Usar credito
	'use_credit_in_orders' => false, // Utilizar credito para validar las ordenes
	'depositPct' => null, // porcentaje que corresponde al deposito - se relaciona con payDepositTpv
	'edit_orders' => false, // Modificar orden en ficha w
	'check_adjudications_for_ries_by_auction' => false, //Comporbar para el importe máximo de adjudicación la suba de adjudicaciones de la subasta entera
	'default_category' => null, // Categoria que se cargará por defecto en listado si no existe ninguna seleccionada
	'free_shipping_costs' => null, //No cobra los gastos de envio en los lotes de las subastas introducidas
	'orderby_allbidsandorders' => null, //Indica el orden en el que apareceran las pujas
	'redirect_auction_finish_to_home' => false, //Redirecciones a la home cuando una subasta no existe o a finalizado
	'redirect_home_nolot' => false, // Redirigir a home, si no encuentra ficha lote
	'searchField' => null, // Campos por los que realizará la busqueda de texto en el grid
	'searchLongWord' => 2, // numero de caracteres mínimos que debe tener una palabra para que la busque, si tiene menos de ese valor será rechazada
	'seconds_automatic_auction' => 5, // Número de segundos que tardará en ejecutarse automáticamente el contador de tiempo atras de la subasta
	'user_bid_lotList' => false, // en grid de lotes, llega user_have_bid si este a pujado por el lote
	'enable_tr_auctions' => true, // Habilitar subastas en tiempo real

	/*
    |--------------------------------------------------------------------------
    |  Legacy / Pendiente de eliminar
    |--------------------------------------------------------------------------
    */
	'order_by_filter' => 'precio_salida', //@todo - grid antiguo.
	'pujas_maximas_mostradas' => -1, //@todo - todos tienen -1
	'force_language_redirect' => false, //@todo - Mirar alcala/duran/gutinvest y ves si se puede eliminar.
	'email_bid_confirmed' => '', //Antiguo email de confirmacion de puja. Alcala, gutinvest y soporte.
	'required_invoice_pay_lot' => false, // Para que un lote aparezca como pagado se requiere que esté facturado @todo - solo tau y desactivado
	'subastas_activas' => null, // Indicar que subastas tipo de subastas se tienen que mostrar en subastas_activas @todo - Solo tau y está página no la tienen.
];
