<?php

return [
	'add_calendar_feature' => 0,
	'awarded' => 1,
	'default_theme' => '',
	'deleteBids' => 1,
	'exchange' => 1,
	'gridLots' => false,
	'img_lot' => '/img', //@todo - Esta configurado en app.php
	'new_image_folders' => true, //@todo - Todos los tienen en 1. Eliminar lógica antigua
	'max_bids' => 4,
	'pagination_bills' => 8,
	'tranferCount' => '',
	'tr_show_adjudicaciones' => true,
	'tr_show_automatic_auction' => true,
	'tr_show_buscador' => true,
	'tr_show_canel_bid_client' => false,
	'tr_show_chat' => true,
	'tr_show_estimate_price' => true,
	'tr_show_ordenes_licitacion' => true,
	'tr_show_pujas' => true,
	'tr_show_streaming' => false,
	'video_home' => false, //Activar video/matteport home
	'news_relacionadas' => 3, //Número de noticias relacionadas a mostrar
	'paginate_blog' => 16, //Número de entradas por página en el blog
	'impsalhces_asigl0' => false, //En la parilla de lotes se vera precio salida "impsalhces_asigl0"
	'estimacion' => false, // En la parilla de lotes se vera estimacion "imptas_asigl0 - imptash_asigl0"
	'ref_asigl0' => false, // En la parilla de lotes se vera referencia del lote "ref_asigl0"
	'descweb_hces1' => false, // En la parilla de lotes se vera descripcion web "descweb_hces1"
	'desc_hces1' => false, // En la parilla de lotes se vera descripcion "desc_hces1"
	'titulo_hces1' => false, // En la parilla de lotes se vera titulo "titulo_hces1"
	'icon_multiple_images' => false, // Muestra un icono en la lista de lotes indicando que ese lote tiene multiples imagenes
	'loadImage' => false, // Fuerza a hace el load de las imágenes.
	'lotlist_img' => null, //Resolución de imagen en listado de lotes
	'seo_in_home' => null, //Seo en home
	'seo_in_contact' => null, //Seo en contacto
	'seo_in_register' => null, //Seo en registro
	'seo_in_valoracion' => null, //Seo en página de valoracion
	'videoEnGrid' => null, //Obtener y mostrar videos de lote en grid
	'hideCloseLots' => null, //Ocultar lotes de venta directa despues de fin fecha
	'hideRetiredLots' => null, //Ocultar retirados del grid
	'gridAllSessions' => null, //Todos los lotes en una sesion
	'tr_priority_to_title' => true, // Dar prioridad a titulo_hces1 sobre descweb_hces1 en tr admin
	'valoracion_index_follow' => false, //Indexar pagina de valoracion articulos
	'articles_per_page' => 12, // Número de artículos a mostrar en listado
	'show_warning_modal' => false, //Mostrar modal de aviso en la web [ansorena]
	'whatsapp_num_button' => null, //En caso de que haya número de teléfono se mostrará el botón que te lleva abrir un chat de whatsapp [ansorena]
	'contat_with_placeholders' => false,// placeholders en inputs de contacto
	'tr_cost_price' => false, // Mostrar precio de coste en el tiempo real.
	'tr_hidden_description' => false, // Ocultar descripción en tiempo real. @todo - No lo esta usando nadie, pero borrar con cuidado ya que afecta el tiempo real.
	'tr_hidden_title' => false, // Ocultar título del lote en el tiempo real.
	'PropietarioTR' => false, // Que aparezca el propietario de los lotes en el tiempo real del administrador
	'bisOnlyIn' => null, // mostrar solo el bis en este tipo de subastas. ejemplo: 'W',
	'bis' => null, // se usa para indicar que los lotes pueden tener bis, y hay que indicar por que valor empieza, si por A o por B
	'noindexInfoAuction' => false, //No indexa la página de informacion de la subasta
	'tr_fairwarning' => false, // Mostrar botón de Fair Warning en el administrador del tiempo real
	'seo_in_search' => false, // Texto seo en busquedaController
	'not_compress_real_image' => false, // No comprimir imagen real
	'btnPujarHoras' => 0, //tiempo previo, en horas, de inicio de la subasta para mostrar botón de pujar en vivo.
	'conent_to_all_blog' => false, //Obtener y mostrar contenido blob en el listado de entradas del blog,
	'most_distant_blog_date' => null, // Fecha más lejana para mostrar entradas del blog
	'always_alert_bid' => false, // Comunicar con un sonido siempre que haya puja
	'extra_conservation' => false, // Mostrar conservacion en ficha
	'generate_image_when_not_found' => false, // Se fuerza a genera la miniatura si esta no existe.
	'higher_bid_tr' => false, // No mostrar notificación de sobrepuja en tiempo real. (En true, no se muestra!)
	'seo_notlogged_page' => false, //Tener seo en la pagina not-logged
	'show_rarity_in_grid' => false, // Mostrar rareza en grid de lotes
];
