<?php

return [
	'brandIdUP2' => null,
	'brandIdUP2_test' => null,
	'environmentUP2' => false,
	'merchantIdUP2' => null,
	'merchantIdUP2_test' => null,
	'passwordUP2' => null,
	'passwordUP2_test' => null,
	'UP2_cancel' => '/es/pagina/pago-cancelado',
	'UP2_return' => '/es/pagina/pago-realizado',
	'captcha_v3_private' => '',
	'captcha_v3_public' => '',
	'captcha_v3_severity' => '0.6',
	'deliverea_api_testpass' => null,
	'deliverea_api_testuser' => null,
	'deliverea_sandbox' => null,
	'google_analytics' => null, //@todo, modificar las vistas para utilizar el config.
	'google_conversion_id' => '', //Código remarketing google
	'invaluable_API_password' => '',
	'invaluable_API_URL' => '',
	'invaluable_API_user' => '',
	'invaluableHouse' => '',
	'mailchimp_api_key' => null,
	'mailchimp_list_id' => null,
	'mailchimp_server_prefix' => null,
	'paypalClientId' => null,
	'paypalClientSecret' => null,
	'appIdVottun' => null,
	'urlIpfsVottun' => null,
	'urlNftVottun' => null,
	'urlPowVottun' => null,
	'urlToPackengers' => '',
	'zoho_client_id' => null,
	'zoho_client_secret' => null,
	'zoho_grant_code' => null,
	'zoho_organization_id' => null,
	'zoho_refresh_token' => null,
	'auchouse_code' => null,
	'subalia_cli' => null,
	'subalia_key' => null,
	'subalia_min_licit' => 100000,
	'ps_sb_auth_key' => null,
	'ps_shop_path' => null,
	'ps_ws_auth_key' => null,
	'KeyRedsys' => null, //Clave de firma en redsys de redsys
	'MerchandCodeRedsys' => null, //Codigo de comercio en redsys
	'PaymentUrlKO' => null, //Return payment en caso de error
	'PaymentUrlOK' => null, //Return payment
	'UrlRedsys' => null, //Url de redsys
	'TerminalRedsys' => null, //numero de terminal en redsys
	'APP_SUBALIA_GEMP' => null, //grupo de empresa asociada a subalia
	'APP_SUBALIA_EMP' => null, //empresa de subalia asociada
	'subalia_URL' => null, //url de subalia
	'passwordUP2_Tienda1' => null, //password numismatica
	'brandIdUP2_Tienda1' => null, //Brand Numismatica
	'merchantIdUP2_Tienda1' => null, //Merchand Numismatica
	'passwordUP2_Tienda2' => null, //password Arqueologia
	'brandIdUP2_Tienda2' => null, //Brand Arqueologia
	'merchantIdUP2_Tienda2' => null, //Merchand Arqueologia
	'multiPasarela' => null, //Multiples pasarelas
	'streaming_id' => null, //Id de websocket de streaming,
	'streaming_name' => null, //Nombre de ruta del streaming.
	'privatechanel_hash_password' => null, //hash password acceso a canal privado
	'privatechanel_user' => null, //usuario acceso a canal privado
	'endpointWS' => null, //endpoint del websocket
	'nftPayNetwork' => null, //Si una obra se mintea o transfiere desde una de estas redes se deberá cobrar el minteo al propietario y la transferencia al comprador
	'VottunComission' => 0, // Porcentaje de comisión que aplica Vottun por le minteo y la transferencia
];
