<?php

return [
	'catalogo_newsletter' => null,
	'coregistroSubalia' => false,
	'DeleteOrders' => false,
	'delivery_address' => false,
	'fpag_default' => 0,
	'fpag_foreign_default' => null,
	'login_acces_web' => 0, //@todo - eliminar.
	'login_attempts_timeout' => 60,
	'login_attempts' => 0,
	'makePreferences' => 0,
	'modal_login' => 0,
	'new_favorites_panel' => 0,
	'panel_password_recovery' => 1, //@todo - todos en 1.
	'pasarela_web' => false,
	'paymentPaypal' => false,
	'paymentUP2' => null,
	'PayTransfer' => false,
	'registerCheckerF' => '',
	'registerCheckerJ' => '',
	'registration_disabled' => false,
	'regtype' => 1,
	'token_security' => 'medium',
	'user_panel_group_subasta' => 1, //@todo - Todos lo tienen a 1
	'userPanelCIFandCC' => null, //@todo - Revisar si es necesario.
	'userPanelMySales' => null,
	'web_gastos_envio' => null,
	'ps_activate' => false, //@todo Revisar su uso.
	'name_without_coma' => false,
	'strtodefault_register' => false,
	'ries_cli' => 0, //@todo - Se utilizaba para el riesgo al registrarse, pero ya se puede eliminar
	'registro_user_w' => false, //Un usuario se registra en el codigo del cliente pone W delante ejemplo: W00001
	'no_user_change_info' => false, //No permite al usuario modificar sus datos
	'paymentRedsys' => false, //Habilitar pagos por redsys
	'multi_key_pass' => false, //EL password se encripta con una key para cada usuario
	'allotments_shopping_cart' => null, //Separar adjudicaciones por venta directa y resto
	'multiPasarela' => null, //Multiples pasarelas
	'all_tax_clients' => null, //Forzamos el tipo de iva
	'client_files_erp' => false, // Ruta de archivos establecida desde ERP (fxdir)
	'dni_in_storage' => false, //Indica ruta de almacenamiento del DNI, valores: dni-files, cli-documentation, base-dni-files. @todo, mirar si con el config superior se puede sustituir
	'user_panel_cif' => false, // Guardar imágenes DNI desde el panel de usuario,
	'update_fxcli_exist_client' => false, //Cuando el cliente se da de alta y el cliente ya existe updatemos la información del cliente
	'save_newsletter_in_cliweb' => false, // Guardar newsletter en nllist_1
	'checkPayCart' => false, // Deben acceptar el check para poder pagar en al tienda
	'PayBizum' => false, // Se permite el pago con Bizum
	'direccion_envio' => false, // mostrar direccion envio en carrito
	'SeguroCarrito' => false, // Aparece solo el seguro de envio aunque no se tramite el envio desde la web
	'TaxForEuropean' => false, // Aplica el iva solo a los ciudaanos europeos
	'viewVAuctionAward' => false, // Ver las adjudicaciones de V en el panel de vendidos
	'user_panel_cc' => false, // editar cuenta corriente desde panel usuario
	'multipleNif' => false, // Permite el registro con un nif que ya exista
	'fpag_reply' => false, // Copiar forma de pago (fpag_cli) en fpag2_cli
	'number_orders_salespanel' => false, // Conteo de ordenes en panel de ventas
	'save_address_when_empty' => true, // Crear dirección principal con los datos de facturación en registro cuando este marcado como tal. Por defecto se crea
	'sellAuctionsStartDateOrder' => false, //En panel de ventas, añadir orden por fecha de inicio y seleccionar que dirección de orden. enum: 'false'|'asc'|'desc'
	'show_only_active_auctions' => false, //En panel de ventas, mostrar solo subastas activas y de admin
	'payDepositTpv' => false, // El deposito se deve pagar con tpv
	'multiredsysRsoc' => null, //nos indica que número de digitos debemos coger del principio del Rsoc para identificar la empresa a facturar
	'blockpuj_in_register' => false, //Usuarios se registran con bloqueo de pujas por defecto
	'canarias_0_tax_clients' => 0, //Tax 0 clientes de canarias
	'check_active_auctions' => false, // Revisar si hay subasta activa para permitir o no el registro
	'delete_addres_toupdate' => true, // Borrar linea de direccion al eliminarla del panel
	'licencia_exportacion' => false, //Licencia de exportación en lotes adjudicados
	'lots_closed_inpanel' => false, // Mostrar lotes cerrados en pujas y favoritos del panel
	'no_redirect_register' => false, // no redirigeen registro  si el usuario esta logeado
	'notlogged_page_inpanel' => false, // Mostrar página de iniciar sesión cuando no esta iniciada
	'shipping_label' => 'W1', //Etiqueta con la que se define el codigo de direccion de envío. Por defecto debería ser W1
	'showClosedLotOrdersInPanel' => false, // Mostrar ordenes de lotes cerrados en panel
	'sobreCargoPagoWeb' => false, // Sobrecargo por pago con tarjeta
	'take_gastos_prefact' => false, //Cogemos los gastos extras de esa prefactura si la tiene generada

];
