<?php

return [
	'brandIdUP2' => null,
	'brandIdUP2_test' => null,
	'environmentUP2' => false,
	'merchantIdUP2' => null,
	'merchantIdUP2_test' => null,
	'passwordUP2' => null,
	'passwordUP2_test' => null,
	'UP2_cancel' => '/es/pagina/pago-cancelado',
	'UP2_return' => '/es/pagina/pago-realizado',
	'captcha_v3_private' => '',
	'captcha_v3_public' => '',
	'captcha_v3_severity' => '0.6',
	'deliverea_api_testpass' => null,
	'deliverea_api_testuser' => null,
	'deliverea_sandbox' => null,
	'fb_app_id' => '', //@todo - Eliminar.
	'google_analytics' => null, //@todo, modificar las vistas para utilizar el config.
	'google_conversion_id' => '', //Código remarketing google
	'invaluable_API_password' => '',
	'invaluable_API_URL' => '',
	'invaluable_API_user' => '',
	'invaluableHouse' => '',
	'mailchimp_api_key' => null,
	'mailchimp_list_id' => null,
	'mailchimp_server_prefix' => null,
	'paypalClientId' => null,
	'paypalClientSecret' => null,
	'appIdVottun' => null,
	'urlIpfsVottun' => null,
	'urlNftVottun' => null,
	'urlPowVottun' => null,
	'urlToPackengers' => '',
	'zoho_client_id' => null,
	'zoho_client_secret' => null,
	'zoho_grant_code' => null,
	'zoho_organization_id' => null,
	'zoho_refresh_token' => null,
	'auchouse_code' => null,
	'subalia_cli' => null,
	'subalia_key' => null,
	'subalia_min_licit' => 100000,
	'ps_sb_auth_key' => null,
	'ps_shop_path' => null,
	'ps_ws_auth_key' => null,
	'KeyRedsys' => null, //Clave de firma en redsys de redsys
	'MerchandCodeRedsys' => null, //Codigo de comercio en redsys
	'PaymentUrlKO' => null, //Return payment en caso de error
	'PaymentUrlOK' => null, //Return payment
	'UrlRedsys' => null, //Url de redsys
	'TerminalRedsys' => null, //numero de terminal en redsys
];
